apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: medicure-pod
  name: medicure-pod
spec:
  containers:
  - image: swatista29/myproject11
    name: medicure-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
