apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: medicure-pod
  name: medicure-pod
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30001
  selector:
    run: medicure-pod
  type: NodePort
status:
  loadBalancer: {}
